# Generated by Django 5.2.3 on 2025-06-25 05:26

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritebook',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='cover_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='favoritebook',
            unique_together={('user', 'book_id')},
        ),
    ]
